# Generated by Django 5.1 on 2024-08-21 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('watchlist', models.ManyToManyField(related_name='public_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
