# Generated by Django 5.1 on 2024-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_remove_watchlist_overview_remove_watchlist_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='poster_path',
            new_name='poster_image',
        ),
    ]
