# Generated by Django 5.1 on 2024-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_rename_poster_path_watchlist_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
    ]
