# Generated by Django 5.1 on 2024-08-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
