# Generated by Django 5.1 on 2024-08-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.JSONField(default=list),
        ),
    ]
