# Generated by Django 5.1 on 2024-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_remove_userprofile_favorite_movies_favoritemovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='movie_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
