# Generated by Django 5.1 on 2024-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_alter_favoritemovie_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='poster_image',
            field=models.URLField(null=True),
        ),
    ]
