# Generated by Django 5.1 on 2024-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_alter_favoritemovie_poster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='poster_image',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='title',
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='favorite_movies',
            field=models.JSONField(default=list),
        ),
    ]
