# Generated by Django 5.1 on 2024-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0011_userprofile_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.JSONField(default=list),
        ),
    ]
