# Generated by Django 5.1 on 2024-08-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_remove_userprofile_bookmarks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
